'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace svcItemsMgr
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDescField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorNumField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorDesc() As String
            Get
                Return Me.ErrorDescField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDescField, value) <> true) Then
                    Me.ErrorDescField = value
                    Me.RaisePropertyChanged("ErrorDesc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorNum() As Integer
            Get
                Return Me.ErrorNumField
            End Get
            Set
                If (Me.ErrorNumField.Equals(value) <> true) Then
                    Me.ErrorNumField = value
                    Me.RaisePropertyChanged("ErrorNum")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcFile", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcFile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileContentsField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PKFieldValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CD() As String
            Get
                Return Me.CDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CDField, value) <> true) Then
                    Me.CDField = value
                    Me.RaisePropertyChanged("CD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ED() As String
            Get
                Return Me.EDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EDField, value) <> true) Then
                    Me.EDField = value
                    Me.RaisePropertyChanged("ED")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileContents() As Byte()
            Get
                Return Me.FileContentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileContentsField, value) <> true) Then
                    Me.FileContentsField = value
                    Me.RaisePropertyChanged("FileContents")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameField, value) <> true) Then
                    Me.FileNameField = value
                    Me.RaisePropertyChanged("FileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PKFieldValue() As String
            Get
                Return Me.PKFieldValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PKFieldValueField, value) <> true) Then
                    Me.PKFieldValueField = value
                    Me.RaisePropertyChanged("PKFieldValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DupRule", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib.Enums.Item.Add")>  _
    Public Enum DupRule As Long
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EMails = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PK = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IfDup", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib.Enums.Item.Add")>  _
    Public Enum IfDup As Long
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Add = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Update = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Ignore = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Result", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib.Enums.Item.Add")>  _
    Public Enum Result As Long
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Added = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Updated = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Ignored = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="svcItemsMgr.ISvcItemsMgr")>  _
    Public Interface ISvcItemsMgr
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/NewItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/NewItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/NewItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function NewItem(ByVal EntityID As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/NewItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/NewItemResponse")>  _
        Function NewItemAsync(ByVal EntityID As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/NewItemWithParent", ReplyAction:="http://tempuri.org/ISvcItemsMgr/NewItemWithParentResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/NewItemWithParentdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function NewItemWithParent(ByVal EntityID As String, ByVal ParentPKFieldValue As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/NewItemWithParent", ReplyAction:="http://tempuri.org/ISvcItemsMgr/NewItemWithParentResponse")>  _
        Function NewItemWithParentAsync(ByVal EntityID As String, ByVal ParentPKFieldValue As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/GetItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItem(ByVal PKFieldValue As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemResponse")>  _
        Function GetItemAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/AddItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/AddItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/AddItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AddItem(ByVal EntityID As String, ByVal Item() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/AddItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/AddItemResponse")>  _
        Function AddItemAsync(ByVal EntityID As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/UpdateItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/UpdateItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/UpdateItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function UpdateItem(ByVal EntityID As String, ByVal Item() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/UpdateItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/UpdateItemResponse")>  _
        Function UpdateItemAsync(ByVal EntityID As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/DeleteItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/DeleteItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/DeleteItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function DeleteItem(ByVal EntityID As String, ByVal PKFieldValue As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/DeleteItem", ReplyAction:="http://tempuri.org/ISvcItemsMgr/DeleteItemResponse")>  _
        Function DeleteItemAsync(ByVal EntityID As String, ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/DeleteItems", ReplyAction:="http://tempuri.org/ISvcItemsMgr/DeleteItemsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/DeleteItemsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function DeleteItems(ByVal EntityID As String, ByVal PKFieldValues() As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/DeleteItems", ReplyAction:="http://tempuri.org/ISvcItemsMgr/DeleteItemsResponse")>  _
        Function DeleteItemsAsync(ByVal EntityID As String, ByVal PKFieldValues() As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItemInfo", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemInfoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/GetItemInfodcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItemInfo(ByVal WhichID As String, ByVal PKFieldValue As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItemInfo", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemInfoResponse")>  _
        Function GetItemInfoAsync(ByVal WhichID As String, ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItemFields", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemFieldsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/GetItemFieldsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItemFields(ByVal EntityID As String, ByVal PKFieldValues() As String, ByVal Fields As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItemFields", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemFieldsResponse")>  _
        Function GetItemFieldsAsync(ByVal EntityID As String, ByVal PKFieldValues() As String, ByVal Fields As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItemDoc", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemDocResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/GetItemDocdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItemDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcItemsMgr.dcFile
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItemDoc", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemDocResponse")>  _
        Function GetItemDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcItemsMgr.dcFile)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItemDocUsingOTP", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemDocUsingOTPResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/GetItemDocUsingOTPdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItemDocUsingOTP(ByVal OTP As String, ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcItemsMgr.dcFile
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetItemDocUsingOTP", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetItemDocUsingOTPResponse")>  _
        Function GetItemDocUsingOTPAsync(ByVal OTP As String, ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcItemsMgr.dcFile)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/SetItemDoc", ReplyAction:="http://tempuri.org/ISvcItemsMgr/SetItemDocResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/SetItemDocdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function SetItemDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcItemsMgr.dcFile, ByVal Zipped As Boolean) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/SetItemDoc", ReplyAction:="http://tempuri.org/ISvcItemsMgr/SetItemDocResponse")>  _
        Function SetItemDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcItemsMgr.dcFile, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetCustomizeDoc", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetCustomizeDocResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/GetCustomizeDocdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetCustomizeDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcItemsMgr.dcFile
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetCustomizeDoc", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetCustomizeDocResponse")>  _
        Function GetCustomizeDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcItemsMgr.dcFile)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/SetCustomizeDoc", ReplyAction:="http://tempuri.org/ISvcItemsMgr/SetCustomizeDocResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/SetCustomizeDocdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function SetCustomizeDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcItemsMgr.dcFile, ByVal Zipped As Boolean) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/SetCustomizeDoc", ReplyAction:="http://tempuri.org/ISvcItemsMgr/SetCustomizeDocResponse")>  _
        Function SetCustomizeDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcItemsMgr.dcFile, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/AddItemCBSXML", ReplyAction:="http://tempuri.org/ISvcItemsMgr/AddItemCBSXMLResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/AddItemCBSXMLdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AddItemCBSXML(ByVal EntityID As String, ByVal CBSXML() As Byte) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/AddItemCBSXML", ReplyAction:="http://tempuri.org/ISvcItemsMgr/AddItemCBSXMLResponse")>  _
        Function AddItemCBSXMLAsync(ByVal EntityID As String, ByVal CBSXML() As Byte) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/UpdateItemCBSXML", ReplyAction:="http://tempuri.org/ISvcItemsMgr/UpdateItemCBSXMLResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/UpdateItemCBSXMLdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function UpdateItemCBSXML(ByVal EntityID As String, ByVal CBSXML() As Byte) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/UpdateItemCBSXML", ReplyAction:="http://tempuri.org/ISvcItemsMgr/UpdateItemCBSXMLResponse")>  _
        Function UpdateItemCBSXMLAsync(ByVal EntityID As String, ByVal CBSXML() As Byte) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/AddUpdateItemCBSXML", ReplyAction:="http://tempuri.org/ISvcItemsMgr/AddUpdateItemCBSXMLResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/AddUpdateItemCBSXMLdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AddUpdateItemCBSXML(ByVal request As svcItemsMgr.AddUpdateItemCBSXMLRequest) As svcItemsMgr.AddUpdateItemCBSXMLResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/AddUpdateItemCBSXML", ReplyAction:="http://tempuri.org/ISvcItemsMgr/AddUpdateItemCBSXMLResponse")>  _
        Function AddUpdateItemCBSXMLAsync(ByVal request As svcItemsMgr.AddUpdateItemCBSXMLRequest) As System.Threading.Tasks.Task(Of svcItemsMgr.AddUpdateItemCBSXMLResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetNewPK", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetNewPKResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/GetNewPKdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetNewPK(ByVal EntityID As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetNewPK", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetNewPKResponse")>  _
        Function GetNewPKAsync(ByVal EntityID As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/IsItemExist", ReplyAction:="http://tempuri.org/ISvcItemsMgr/IsItemExistResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/IsItemExistdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function IsItemExist(ByVal EntityIDs() As String, ByVal DupRule As svcItemsMgr.DupRule, ByVal SearchValues() As String, ByVal Modifiable As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/IsItemExist", ReplyAction:="http://tempuri.org/ISvcItemsMgr/IsItemExistResponse")>  _
        Function IsItemExistAsync(ByVal EntityIDs() As String, ByVal DupRule As svcItemsMgr.DupRule, ByVal SearchValues() As String, ByVal Modifiable As Boolean) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetPKValuesUsingExtIDWords", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetPKValuesUsingExtIDWordsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/GetPKValuesUsingExtIDWordsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetPKValuesUsingExtIDWords(ByVal EntityID As String, ByVal WordsString As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/GetPKValuesUsingExtIDWords", ReplyAction:="http://tempuri.org/ISvcItemsMgr/GetPKValuesUsingExtIDWordsResponse")>  _
        Function GetPKValuesUsingExtIDWordsAsync(ByVal EntityID As String, ByVal WordsString As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/MultiEdits", ReplyAction:="http://tempuri.org/ISvcItemsMgr/MultiEditsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcItemsMgr.dcException), Action:="http://tempuri.org/ISvcItemsMgr/MultiEditsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function MultiEdits(ByVal EntityID As String, ByVal Which As String, ByVal WhichID As String, ByVal FilterBy As String, ByVal MultiEditXML As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcItemsMgr/MultiEdits", ReplyAction:="http://tempuri.org/ISvcItemsMgr/MultiEditsResponse")>  _
        Function MultiEditsAsync(ByVal EntityID As String, ByVal Which As String, ByVal WhichID As String, ByVal FilterBy As String, ByVal MultiEditXML As String) As System.Threading.Tasks.Task(Of Long)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AddUpdateItemCBSXML", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class AddUpdateItemCBSXMLRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EntityID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public CBSXML() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public DupRule As svcItemsMgr.DupRule
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public IfDup As svcItemsMgr.IfDup
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public Result As svcItemsMgr.Result
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public PKFieldValue As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EntityID As String, ByVal CBSXML() As Byte, ByVal DupRule As svcItemsMgr.DupRule, ByVal IfDup As svcItemsMgr.IfDup, ByVal Result As svcItemsMgr.Result, ByVal PKFieldValue As String)
            MyBase.New
            Me.EntityID = EntityID
            Me.CBSXML = CBSXML
            Me.DupRule = DupRule
            Me.IfDup = IfDup
            Me.Result = Result
            Me.PKFieldValue = PKFieldValue
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AddUpdateItemCBSXMLResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class AddUpdateItemCBSXMLResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Result As svcItemsMgr.Result
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public PKFieldValue As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Result As svcItemsMgr.Result, ByVal PKFieldValue As String)
            MyBase.New
            Me.Result = Result
            Me.PKFieldValue = PKFieldValue
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISvcItemsMgrChannel
        Inherits svcItemsMgr.ISvcItemsMgr, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SvcItemsMgrClient
        Inherits System.ServiceModel.ClientBase(Of svcItemsMgr.ISvcItemsMgr)
        Implements svcItemsMgr.ISvcItemsMgr
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function NewItem(ByVal EntityID As String) As Byte() Implements svcItemsMgr.ISvcItemsMgr.NewItem
            Return MyBase.Channel.NewItem(EntityID)
        End Function
        
        Public Function NewItemAsync(ByVal EntityID As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcItemsMgr.ISvcItemsMgr.NewItemAsync
            Return MyBase.Channel.NewItemAsync(EntityID)
        End Function
        
        Public Function NewItemWithParent(ByVal EntityID As String, ByVal ParentPKFieldValue As String) As Byte() Implements svcItemsMgr.ISvcItemsMgr.NewItemWithParent
            Return MyBase.Channel.NewItemWithParent(EntityID, ParentPKFieldValue)
        End Function
        
        Public Function NewItemWithParentAsync(ByVal EntityID As String, ByVal ParentPKFieldValue As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcItemsMgr.ISvcItemsMgr.NewItemWithParentAsync
            Return MyBase.Channel.NewItemWithParentAsync(EntityID, ParentPKFieldValue)
        End Function
        
        Public Function GetItem(ByVal PKFieldValue As String) As Byte() Implements svcItemsMgr.ISvcItemsMgr.GetItem
            Return MyBase.Channel.GetItem(PKFieldValue)
        End Function
        
        Public Function GetItemAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcItemsMgr.ISvcItemsMgr.GetItemAsync
            Return MyBase.Channel.GetItemAsync(PKFieldValue)
        End Function
        
        Public Function AddItem(ByVal EntityID As String, ByVal Item() As Byte) As Boolean Implements svcItemsMgr.ISvcItemsMgr.AddItem
            Return MyBase.Channel.AddItem(EntityID, Item)
        End Function
        
        Public Function AddItemAsync(ByVal EntityID As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcItemsMgr.ISvcItemsMgr.AddItemAsync
            Return MyBase.Channel.AddItemAsync(EntityID, Item)
        End Function
        
        Public Function UpdateItem(ByVal EntityID As String, ByVal Item() As Byte) As Boolean Implements svcItemsMgr.ISvcItemsMgr.UpdateItem
            Return MyBase.Channel.UpdateItem(EntityID, Item)
        End Function
        
        Public Function UpdateItemAsync(ByVal EntityID As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcItemsMgr.ISvcItemsMgr.UpdateItemAsync
            Return MyBase.Channel.UpdateItemAsync(EntityID, Item)
        End Function
        
        Public Function DeleteItem(ByVal EntityID As String, ByVal PKFieldValue As String) As Boolean Implements svcItemsMgr.ISvcItemsMgr.DeleteItem
            Return MyBase.Channel.DeleteItem(EntityID, PKFieldValue)
        End Function
        
        Public Function DeleteItemAsync(ByVal EntityID As String, ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Boolean) Implements svcItemsMgr.ISvcItemsMgr.DeleteItemAsync
            Return MyBase.Channel.DeleteItemAsync(EntityID, PKFieldValue)
        End Function
        
        Public Function DeleteItems(ByVal EntityID As String, ByVal PKFieldValues() As String) As String() Implements svcItemsMgr.ISvcItemsMgr.DeleteItems
            Return MyBase.Channel.DeleteItems(EntityID, PKFieldValues)
        End Function
        
        Public Function DeleteItemsAsync(ByVal EntityID As String, ByVal PKFieldValues() As String) As System.Threading.Tasks.Task(Of String()) Implements svcItemsMgr.ISvcItemsMgr.DeleteItemsAsync
            Return MyBase.Channel.DeleteItemsAsync(EntityID, PKFieldValues)
        End Function
        
        Public Function GetItemInfo(ByVal WhichID As String, ByVal PKFieldValue As String) As Byte() Implements svcItemsMgr.ISvcItemsMgr.GetItemInfo
            Return MyBase.Channel.GetItemInfo(WhichID, PKFieldValue)
        End Function
        
        Public Function GetItemInfoAsync(ByVal WhichID As String, ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcItemsMgr.ISvcItemsMgr.GetItemInfoAsync
            Return MyBase.Channel.GetItemInfoAsync(WhichID, PKFieldValue)
        End Function
        
        Public Function GetItemFields(ByVal EntityID As String, ByVal PKFieldValues() As String, ByVal Fields As String) As Byte() Implements svcItemsMgr.ISvcItemsMgr.GetItemFields
            Return MyBase.Channel.GetItemFields(EntityID, PKFieldValues, Fields)
        End Function
        
        Public Function GetItemFieldsAsync(ByVal EntityID As String, ByVal PKFieldValues() As String, ByVal Fields As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcItemsMgr.ISvcItemsMgr.GetItemFieldsAsync
            Return MyBase.Channel.GetItemFieldsAsync(EntityID, PKFieldValues, Fields)
        End Function
        
        Public Function GetItemDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcItemsMgr.dcFile Implements svcItemsMgr.ISvcItemsMgr.GetItemDoc
            Return MyBase.Channel.GetItemDoc(EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function GetItemDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcItemsMgr.dcFile) Implements svcItemsMgr.ISvcItemsMgr.GetItemDocAsync
            Return MyBase.Channel.GetItemDocAsync(EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function GetItemDocUsingOTP(ByVal OTP As String, ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcItemsMgr.dcFile Implements svcItemsMgr.ISvcItemsMgr.GetItemDocUsingOTP
            Return MyBase.Channel.GetItemDocUsingOTP(OTP, EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function GetItemDocUsingOTPAsync(ByVal OTP As String, ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcItemsMgr.dcFile) Implements svcItemsMgr.ISvcItemsMgr.GetItemDocUsingOTPAsync
            Return MyBase.Channel.GetItemDocUsingOTPAsync(OTP, EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function SetItemDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcItemsMgr.dcFile, ByVal Zipped As Boolean) As Boolean Implements svcItemsMgr.ISvcItemsMgr.SetItemDoc
            Return MyBase.Channel.SetItemDoc(EntityID, PKFieldValue, objDCFile, Zipped)
        End Function
        
        Public Function SetItemDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcItemsMgr.dcFile, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of Boolean) Implements svcItemsMgr.ISvcItemsMgr.SetItemDocAsync
            Return MyBase.Channel.SetItemDocAsync(EntityID, PKFieldValue, objDCFile, Zipped)
        End Function
        
        Public Function GetCustomizeDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcItemsMgr.dcFile Implements svcItemsMgr.ISvcItemsMgr.GetCustomizeDoc
            Return MyBase.Channel.GetCustomizeDoc(EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function GetCustomizeDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcItemsMgr.dcFile) Implements svcItemsMgr.ISvcItemsMgr.GetCustomizeDocAsync
            Return MyBase.Channel.GetCustomizeDocAsync(EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function SetCustomizeDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcItemsMgr.dcFile, ByVal Zipped As Boolean) As Boolean Implements svcItemsMgr.ISvcItemsMgr.SetCustomizeDoc
            Return MyBase.Channel.SetCustomizeDoc(EntityID, PKFieldValue, objDCFile, Zipped)
        End Function
        
        Public Function SetCustomizeDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcItemsMgr.dcFile, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of Boolean) Implements svcItemsMgr.ISvcItemsMgr.SetCustomizeDocAsync
            Return MyBase.Channel.SetCustomizeDocAsync(EntityID, PKFieldValue, objDCFile, Zipped)
        End Function
        
        Public Function AddItemCBSXML(ByVal EntityID As String, ByVal CBSXML() As Byte) As String Implements svcItemsMgr.ISvcItemsMgr.AddItemCBSXML
            Return MyBase.Channel.AddItemCBSXML(EntityID, CBSXML)
        End Function
        
        Public Function AddItemCBSXMLAsync(ByVal EntityID As String, ByVal CBSXML() As Byte) As System.Threading.Tasks.Task(Of String) Implements svcItemsMgr.ISvcItemsMgr.AddItemCBSXMLAsync
            Return MyBase.Channel.AddItemCBSXMLAsync(EntityID, CBSXML)
        End Function
        
        Public Function UpdateItemCBSXML(ByVal EntityID As String, ByVal CBSXML() As Byte) As String Implements svcItemsMgr.ISvcItemsMgr.UpdateItemCBSXML
            Return MyBase.Channel.UpdateItemCBSXML(EntityID, CBSXML)
        End Function
        
        Public Function UpdateItemCBSXMLAsync(ByVal EntityID As String, ByVal CBSXML() As Byte) As System.Threading.Tasks.Task(Of String) Implements svcItemsMgr.ISvcItemsMgr.UpdateItemCBSXMLAsync
            Return MyBase.Channel.UpdateItemCBSXMLAsync(EntityID, CBSXML)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function svcItemsMgr_ISvcItemsMgr_AddUpdateItemCBSXML(ByVal request As svcItemsMgr.AddUpdateItemCBSXMLRequest) As svcItemsMgr.AddUpdateItemCBSXMLResponse Implements svcItemsMgr.ISvcItemsMgr.AddUpdateItemCBSXML
            Return MyBase.Channel.AddUpdateItemCBSXML(request)
        End Function
        
        Public Sub AddUpdateItemCBSXML(ByVal EntityID As String, ByVal CBSXML() As Byte, ByVal DupRule As svcItemsMgr.DupRule, ByVal IfDup As svcItemsMgr.IfDup, ByRef Result As svcItemsMgr.Result, ByRef PKFieldValue As String)
            Dim inValue As svcItemsMgr.AddUpdateItemCBSXMLRequest = New svcItemsMgr.AddUpdateItemCBSXMLRequest()
            inValue.EntityID = EntityID
            inValue.CBSXML = CBSXML
            inValue.DupRule = DupRule
            inValue.IfDup = IfDup
            inValue.Result = Result
            inValue.PKFieldValue = PKFieldValue
            Dim retVal As svcItemsMgr.AddUpdateItemCBSXMLResponse = CType(Me,svcItemsMgr.ISvcItemsMgr).AddUpdateItemCBSXML(inValue)
            Result = retVal.Result
            PKFieldValue = retVal.PKFieldValue
        End Sub
        
        Public Function AddUpdateItemCBSXMLAsync(ByVal request As svcItemsMgr.AddUpdateItemCBSXMLRequest) As System.Threading.Tasks.Task(Of svcItemsMgr.AddUpdateItemCBSXMLResponse) Implements svcItemsMgr.ISvcItemsMgr.AddUpdateItemCBSXMLAsync
            Return MyBase.Channel.AddUpdateItemCBSXMLAsync(request)
        End Function
        
        Public Function GetNewPK(ByVal EntityID As String) As String Implements svcItemsMgr.ISvcItemsMgr.GetNewPK
            Return MyBase.Channel.GetNewPK(EntityID)
        End Function
        
        Public Function GetNewPKAsync(ByVal EntityID As String) As System.Threading.Tasks.Task(Of String) Implements svcItemsMgr.ISvcItemsMgr.GetNewPKAsync
            Return MyBase.Channel.GetNewPKAsync(EntityID)
        End Function
        
        Public Function IsItemExist(ByVal EntityIDs() As String, ByVal DupRule As svcItemsMgr.DupRule, ByVal SearchValues() As String, ByVal Modifiable As Boolean) As String Implements svcItemsMgr.ISvcItemsMgr.IsItemExist
            Return MyBase.Channel.IsItemExist(EntityIDs, DupRule, SearchValues, Modifiable)
        End Function
        
        Public Function IsItemExistAsync(ByVal EntityIDs() As String, ByVal DupRule As svcItemsMgr.DupRule, ByVal SearchValues() As String, ByVal Modifiable As Boolean) As System.Threading.Tasks.Task(Of String) Implements svcItemsMgr.ISvcItemsMgr.IsItemExistAsync
            Return MyBase.Channel.IsItemExistAsync(EntityIDs, DupRule, SearchValues, Modifiable)
        End Function
        
        Public Function GetPKValuesUsingExtIDWords(ByVal EntityID As String, ByVal WordsString As String) As String() Implements svcItemsMgr.ISvcItemsMgr.GetPKValuesUsingExtIDWords
            Return MyBase.Channel.GetPKValuesUsingExtIDWords(EntityID, WordsString)
        End Function
        
        Public Function GetPKValuesUsingExtIDWordsAsync(ByVal EntityID As String, ByVal WordsString As String) As System.Threading.Tasks.Task(Of String()) Implements svcItemsMgr.ISvcItemsMgr.GetPKValuesUsingExtIDWordsAsync
            Return MyBase.Channel.GetPKValuesUsingExtIDWordsAsync(EntityID, WordsString)
        End Function
        
        Public Function MultiEdits(ByVal EntityID As String, ByVal Which As String, ByVal WhichID As String, ByVal FilterBy As String, ByVal MultiEditXML As String) As Long Implements svcItemsMgr.ISvcItemsMgr.MultiEdits
            Return MyBase.Channel.MultiEdits(EntityID, Which, WhichID, FilterBy, MultiEditXML)
        End Function
        
        Public Function MultiEditsAsync(ByVal EntityID As String, ByVal Which As String, ByVal WhichID As String, ByVal FilterBy As String, ByVal MultiEditXML As String) As System.Threading.Tasks.Task(Of Long) Implements svcItemsMgr.ISvcItemsMgr.MultiEditsAsync
            Return MyBase.Channel.MultiEditsAsync(EntityID, Which, WhichID, FilterBy, MultiEditXML)
        End Function
    End Class
End Namespace
