'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace svcLinkedItemsMgr
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(svcLinkedItemsMgr.dcSendEMailException))>  _
    Partial Public Class dcException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDescField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorNumField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorDesc() As String
            Get
                Return Me.ErrorDescField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDescField, value) <> true) Then
                    Me.ErrorDescField = value
                    Me.RaisePropertyChanged("ErrorDesc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorNum() As Integer
            Get
                Return Me.ErrorNumField
            End Get
            Set
                If (Me.ErrorNumField.Equals(value) <> true) Then
                    Me.ErrorNumField = value
                    Me.RaisePropertyChanged("ErrorNum")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcSendEMailException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcSendEMailException
        Inherits svcLinkedItemsMgr.dcException
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OBRespField As svcLinkedItemsMgr.dcOBResp
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OBResp() As svcLinkedItemsMgr.dcOBResp
            Get
                Return Me.OBRespField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OBRespField, value) <> true) Then
                    Me.OBRespField = value
                    Me.RaisePropertyChanged("OBResp")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcOBResp", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcOBResp
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExceptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastTryDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NtriesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OBIntIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Exception() As String
            Get
                Return Me.ExceptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExceptionField, value) <> true) Then
                    Me.ExceptionField = value
                    Me.RaisePropertyChanged("Exception")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastTryDate() As Date
            Get
                Return Me.LastTryDateField
            End Get
            Set
                If (Me.LastTryDateField.Equals(value) <> true) Then
                    Me.LastTryDateField = value
                    Me.RaisePropertyChanged("LastTryDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ntries() As Integer
            Get
                Return Me.NtriesField
            End Get
            Set
                If (Me.NtriesField.Equals(value) <> true) Then
                    Me.NtriesField = value
                    Me.RaisePropertyChanged("Ntries")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OBIntID() As String
            Get
                Return Me.OBIntIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OBIntIDField, value) <> true) Then
                    Me.OBIntIDField = value
                    Me.RaisePropertyChanged("OBIntID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcFile", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcFile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileContentsField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PKFieldValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CD() As String
            Get
                Return Me.CDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CDField, value) <> true) Then
                    Me.CDField = value
                    Me.RaisePropertyChanged("CD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ED() As String
            Get
                Return Me.EDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EDField, value) <> true) Then
                    Me.EDField = value
                    Me.RaisePropertyChanged("ED")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileContents() As Byte()
            Get
                Return Me.FileContentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileContentsField, value) <> true) Then
                    Me.FileContentsField = value
                    Me.RaisePropertyChanged("FileContents")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameField, value) <> true) Then
                    Me.FileNameField = value
                    Me.RaisePropertyChanged("FileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PKFieldValue() As String
            Get
                Return Me.PKFieldValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PKFieldValueField, value) <> true) Then
                    Me.PKFieldValueField = value
                    Me.RaisePropertyChanged("PKFieldValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcMailItem", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcMailItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttachmentsField() As svcLinkedItemsMgr.dcFile
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BCCsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BodyField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirectionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileExtField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPrivateField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MailClientField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MailContentField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MailDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MailTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ParentPKFieldValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReadReceiptField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReturnReceiptField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SentFromEMailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SentFromNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SentToEMailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SentToNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubjectField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UrgentField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDsField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Attachments() As svcLinkedItemsMgr.dcFile()
            Get
                Return Me.AttachmentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AttachmentsField, value) <> true) Then
                    Me.AttachmentsField = value
                    Me.RaisePropertyChanged("Attachments")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BCCs() As String
            Get
                Return Me.BCCsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BCCsField, value) <> true) Then
                    Me.BCCsField = value
                    Me.RaisePropertyChanged("BCCs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Body() As Byte()
            Get
                Return Me.BodyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BodyField, value) <> true) Then
                    Me.BodyField = value
                    Me.RaisePropertyChanged("Body")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCs() As String
            Get
                Return Me.CCsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCsField, value) <> true) Then
                    Me.CCsField = value
                    Me.RaisePropertyChanged("CCs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Direction() As String
            Get
                Return Me.DirectionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirectionField, value) <> true) Then
                    Me.DirectionField = value
                    Me.RaisePropertyChanged("Direction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileExt() As String
            Get
                Return Me.FileExtField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileExtField, value) <> true) Then
                    Me.FileExtField = value
                    Me.RaisePropertyChanged("FileExt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPrivate() As Boolean
            Get
                Return Me.IsPrivateField
            End Get
            Set
                If (Me.IsPrivateField.Equals(value) <> true) Then
                    Me.IsPrivateField = value
                    Me.RaisePropertyChanged("IsPrivate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MailClient() As String
            Get
                Return Me.MailClientField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MailClientField, value) <> true) Then
                    Me.MailClientField = value
                    Me.RaisePropertyChanged("MailClient")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MailContent() As Byte()
            Get
                Return Me.MailContentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MailContentField, value) <> true) Then
                    Me.MailContentField = value
                    Me.RaisePropertyChanged("MailContent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MailDate() As Date
            Get
                Return Me.MailDateField
            End Get
            Set
                If (Me.MailDateField.Equals(value) <> true) Then
                    Me.MailDateField = value
                    Me.RaisePropertyChanged("MailDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MailType() As String
            Get
                Return Me.MailTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MailTypeField, value) <> true) Then
                    Me.MailTypeField = value
                    Me.RaisePropertyChanged("MailType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ParentPKFieldValue() As String
            Get
                Return Me.ParentPKFieldValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ParentPKFieldValueField, value) <> true) Then
                    Me.ParentPKFieldValueField = value
                    Me.RaisePropertyChanged("ParentPKFieldValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReadReceipt() As Boolean
            Get
                Return Me.ReadReceiptField
            End Get
            Set
                If (Me.ReadReceiptField.Equals(value) <> true) Then
                    Me.ReadReceiptField = value
                    Me.RaisePropertyChanged("ReadReceipt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReturnReceipt() As Boolean
            Get
                Return Me.ReturnReceiptField
            End Get
            Set
                If (Me.ReturnReceiptField.Equals(value) <> true) Then
                    Me.ReturnReceiptField = value
                    Me.RaisePropertyChanged("ReturnReceipt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SentFromEMail() As String
            Get
                Return Me.SentFromEMailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SentFromEMailField, value) <> true) Then
                    Me.SentFromEMailField = value
                    Me.RaisePropertyChanged("SentFromEMail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SentFromName() As String
            Get
                Return Me.SentFromNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SentFromNameField, value) <> true) Then
                    Me.SentFromNameField = value
                    Me.RaisePropertyChanged("SentFromName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SentToEMail() As String
            Get
                Return Me.SentToEMailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SentToEMailField, value) <> true) Then
                    Me.SentToEMailField = value
                    Me.RaisePropertyChanged("SentToEMail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SentToName() As String
            Get
                Return Me.SentToNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SentToNameField, value) <> true) Then
                    Me.SentToNameField = value
                    Me.RaisePropertyChanged("SentToName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Subject() As String
            Get
                Return Me.SubjectField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubjectField, value) <> true) Then
                    Me.SubjectField = value
                    Me.RaisePropertyChanged("Subject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Urgent() As Boolean
            Get
                Return Me.UrgentField
            End Get
            Set
                If (Me.UrgentField.Equals(value) <> true) Then
                    Me.UrgentField = value
                    Me.RaisePropertyChanged("Urgent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserIDs() As String
            Get
                Return Me.UserIDsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIDsField, value) <> true) Then
                    Me.UserIDsField = value
                    Me.RaisePropertyChanged("UserIDs")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcSMTPServer", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcSMTPServer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AccountNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EnableSSLField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HostField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PortField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReplyToField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsernameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AccountName() As String
            Get
                Return Me.AccountNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountNameField, value) <> true) Then
                    Me.AccountNameField = value
                    Me.RaisePropertyChanged("AccountName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EnableSSL() As Boolean
            Get
                Return Me.EnableSSLField
            End Get
            Set
                If (Me.EnableSSLField.Equals(value) <> true) Then
                    Me.EnableSSLField = value
                    Me.RaisePropertyChanged("EnableSSL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Host() As String
            Get
                Return Me.HostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HostField, value) <> true) Then
                    Me.HostField = value
                    Me.RaisePropertyChanged("Host")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Port() As Integer
            Get
                Return Me.PortField
            End Get
            Set
                If (Me.PortField.Equals(value) <> true) Then
                    Me.PortField = value
                    Me.RaisePropertyChanged("Port")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReplyTo() As String
            Get
                Return Me.ReplyToField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReplyToField, value) <> true) Then
                    Me.ReplyToField = value
                    Me.RaisePropertyChanged("ReplyTo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="svcLinkedItemsMgr.ISvcLinkedItemsMgr")>  _
    Public Interface ISvcLinkedItemsMgr
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/NewItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/NewItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/NewItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function NewItem(ByVal EntityID As String, ByVal SubEntityID As String, ByVal ParentPKFieldValue As String, ByVal ViewFKs() As String, ByVal XTabFKs() As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/NewItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/NewItemResponse")>  _
        Function NewItemAsync(ByVal EntityID As String, ByVal SubEntityID As String, ByVal ParentPKFieldValue As String, ByVal ViewFKs() As String, ByVal XTabFKs() As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItem(ByVal PKFieldValue As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemResponse")>  _
        Function GetItemAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/AddItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AddItem(ByVal EntityID As String, ByVal Item() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/AddItemResponse")>  _
        Function AddItemAsync(ByVal EntityID As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddItemBatch", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/AddItemBatchResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddItemBatchdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AddItemBatch(ByVal EntityID As String, ByVal Item() As Byte, ByVal OtherParentPKFieldValues() As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddItemBatch", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/AddItemBatchResponse")>  _
        Function AddItemBatchAsync(ByVal EntityID As String, ByVal Item() As Byte, ByVal OtherParentPKFieldValues() As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function UpdateItem(ByVal EntityID As String, ByVal Item() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateItemResponse")>  _
        Function UpdateItemAsync(ByVal EntityID As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function DeleteItem(ByVal EntityID As String, ByVal PKFieldValue As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteItemResponse")>  _
        Function DeleteItemAsync(ByVal EntityID As String, ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemInfo", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemInfoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemInfodcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItemInfo(ByVal PKFieldValue As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemInfo", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemInfoResponse")>  _
        Function GetItemInfoAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetSubEntityID", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetSubEntityIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetSubEntityIDdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetSubEntityID(ByVal PKFieldValue As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetSubEntityID", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetSubEntityIDResponse")>  _
        Function GetSubEntityIDAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/SnoozeCalendarItems", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/SnoozeCalendarItemsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/SnoozeCalendarItemsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function SnoozeCalendarItems(ByVal PKFieldValues() As String, ByVal RemDateTime As Date) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/SnoozeCalendarItems", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/SnoozeCalendarItemsResponse")>  _
        Function SnoozeCalendarItemsAsync(ByVal PKFieldValues() As String, ByVal RemDateTime As Date) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/CompleteCalendarItems", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/CompleteCalendarItemsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/CompleteCalendarItemsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function CompleteCalendarItems(ByVal PKFieldValues() As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/CompleteCalendarItems", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/CompleteCalendarItemsResponse")>  _
        Function CompleteCalendarItemsAsync(ByVal PKFieldValues() As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetCalendarItemsLinkInfo", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetCalendarItemsLinkInfoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetCalendarItemsLinkInfodcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetCalendarItemsLinkInfo(ByVal PKFieldValues() As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetCalendarItemsLinkInfo", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetCalendarItemsLinkInfoResponse")>  _
        Function GetCalendarItemsLinkInfoAsync(ByVal PKFieldValues() As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDoc", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDocResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDocdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItemDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcLinkedItemsMgr.dcFile
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDoc", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDocResponse")>  _
        Function GetItemDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcFile)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDocUsingOTP", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDocUsingOTPResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDocUsingOTPdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetItemDocUsingOTP(ByVal OTP As String, ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcLinkedItemsMgr.dcFile
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDocUsingOTP", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetItemDocUsingOTPResponse")>  _
        Function GetItemDocUsingOTPAsync(ByVal OTP As String, ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcFile)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/SetItemDoc", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/SetItemDocResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/SetItemDocdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function SetItemDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcLinkedItemsMgr.dcFile, ByVal Zipped As Boolean) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/SetItemDoc", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/SetItemDocResponse")>  _
        Function SetItemDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcLinkedItemsMgr.dcFile, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddMailItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/AddMailItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddMailItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AddMailItem(ByVal EntityID As String, ByVal ParentPKFieldValues() As String, ByVal objMailItem As svcLinkedItemsMgr.dcMailItem) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddMailItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/AddMailItemResponse")>  _
        Function AddMailItemAsync(ByVal EntityID As String, ByVal ParentPKFieldValues() As String, ByVal objMailItem As svcLinkedItemsMgr.dcMailItem) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetMailItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetMailItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetMailItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetMailItem(ByVal PKFieldValue As String, ByVal NeedAttachmentsFileContent As Boolean, ByVal NeedMessageFileContent As Boolean) As svcLinkedItemsMgr.dcMailItem
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetMailItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetMailItemResponse")>  _
        Function GetMailItemAsync(ByVal PKFieldValue As String, ByVal NeedAttachmentsFileContent As Boolean, ByVal NeedMessageFileContent As Boolean) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcMailItem)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/SubmittedConsultantsByEMail", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/SubmittedConsultantsByEMailResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/SubmittedConsultantsByEMaildcExceptionFault"& _ 
            "", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function SubmittedConsultantsByEMail(ByVal ConsPKValues() As String, ByVal EMailPKValues() As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/SubmittedConsultantsByEMail", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/SubmittedConsultantsByEMailResponse")>  _
        Function SubmittedConsultantsByEMailAsync(ByVal ConsPKValues() As String, ByVal EMailPKValues() As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/SendEMail", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/SendEMailResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/SendEMaildcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcSendEMailException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/SendEMaildcSendEMailExceptionFault", Name:="dcSendEMailException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function SendEMail(ByVal objMailServer As svcLinkedItemsMgr.dcSMTPServer, ByVal ParentPKValues() As String, ByVal objMailItem As svcLinkedItemsMgr.dcMailItem, ByVal ConsPKValues() As String) As svcLinkedItemsMgr.dcOBResp
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/SendEMail", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/SendEMailResponse")>  _
        Function SendEMailAsync(ByVal objMailServer As svcLinkedItemsMgr.dcSMTPServer, ByVal ParentPKValues() As String, ByVal objMailItem As svcLinkedItemsMgr.dcMailItem, ByVal ConsPKValues() As String) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcOBResp)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/ReSendEMail", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/ReSendEMailResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/ReSendEMaildcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcSendEMailException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/ReSendEMaildcSendEMailExceptionFault", Name:="dcSendEMailException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function ReSendEMail(ByVal objSMTPServer As svcLinkedItemsMgr.dcSMTPServer, ByVal PKFieldValue As String) As svcLinkedItemsMgr.dcOBResp
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/ReSendEMail", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/ReSendEMailResponse")>  _
        Function ReSendEMailAsync(ByVal objSMTPServer As svcLinkedItemsMgr.dcSMTPServer, ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcOBResp)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetOutboxItems", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetOutboxItemsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetOutboxItemsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetOutboxItems() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetOutboxItems", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetOutboxItemsResponse")>  _
        Function GetOutboxItemsAsync() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/EMailError", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/EMailErrorResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/EMailErrordcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Sub EMailError(ByVal Subject As String, ByVal MsgBody As String, ByVal Attachments() As svcLinkedItemsMgr.dcFile)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/EMailError", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/EMailErrorResponse")>  _
        Function EMailErrorAsync(ByVal Subject As String, ByVal MsgBody As String, ByVal Attachments() As svcLinkedItemsMgr.dcFile) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/NewMLinkItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/NewMLinkItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/NewMLinkItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function NewMLinkItem() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/NewMLinkItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/NewMLinkItemResponse")>  _
        Function NewMLinkItemAsync() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetMLinkItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetMLinkItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetMLinkItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetMLinkItem(ByVal PKFieldValue As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/GetMLinkItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/GetMLinkItemResponse")>  _
        Function GetMLinkItemAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateMLinkItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateMLinkItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateMLinkItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function UpdateMLinkItem(ByVal Item() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateMLinkItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/UpdateMLinkItemResponse")>  _
        Function UpdateMLinkItemAsync(ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteMLinkItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteMLinkItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteMLinkItemdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function DeleteMLinkItem(ByVal PKFieldValue As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteMLinkItem", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/DeleteMLinkItemResponse")>  _
        Function DeleteMLinkItemAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddMLinkItems", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/AddMLinkItemsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddMLinkItemsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AddMLinkItems(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Item() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/AddMLinkItems", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/AddMLinkItemsResponse")>  _
        Function AddMLinkItemsAsync(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkSubmitted", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/LinkSubmittedResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkSubmitteddcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Sub LinkSubmitted(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkSubmitted", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/LinkSubmittedResponse")>  _
        Function LinkSubmittedAsync(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkPotential", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/LinkPotentialResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkPotentialdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Sub LinkPotential(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkPotential", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/LinkPotentialResponse")>  _
        Function LinkPotentialAsync(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkReceived", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/LinkReceivedResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcLinkedItemsMgr.dcException), Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkReceiveddcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Sub LinkReceived(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcLinkedItemsMgr/LinkReceived", ReplyAction:="http://tempuri.org/ISvcLinkedItemsMgr/LinkReceivedResponse")>  _
        Function LinkReceivedAsync(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISvcLinkedItemsMgrChannel
        Inherits svcLinkedItemsMgr.ISvcLinkedItemsMgr, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SvcLinkedItemsMgrClient
        Inherits System.ServiceModel.ClientBase(Of svcLinkedItemsMgr.ISvcLinkedItemsMgr)
        Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function NewItem(ByVal EntityID As String, ByVal SubEntityID As String, ByVal ParentPKFieldValue As String, ByVal ViewFKs() As String, ByVal XTabFKs() As String) As Byte() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.NewItem
            Return MyBase.Channel.NewItem(EntityID, SubEntityID, ParentPKFieldValue, ViewFKs, XTabFKs)
        End Function
        
        Public Function NewItemAsync(ByVal EntityID As String, ByVal SubEntityID As String, ByVal ParentPKFieldValue As String, ByVal ViewFKs() As String, ByVal XTabFKs() As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.NewItemAsync
            Return MyBase.Channel.NewItemAsync(EntityID, SubEntityID, ParentPKFieldValue, ViewFKs, XTabFKs)
        End Function
        
        Public Function GetItem(ByVal PKFieldValue As String) As Byte() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetItem
            Return MyBase.Channel.GetItem(PKFieldValue)
        End Function
        
        Public Function GetItemAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetItemAsync
            Return MyBase.Channel.GetItemAsync(PKFieldValue)
        End Function
        
        Public Function AddItem(ByVal EntityID As String, ByVal Item() As Byte) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.AddItem
            Return MyBase.Channel.AddItem(EntityID, Item)
        End Function
        
        Public Function AddItemAsync(ByVal EntityID As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.AddItemAsync
            Return MyBase.Channel.AddItemAsync(EntityID, Item)
        End Function
        
        Public Function AddItemBatch(ByVal EntityID As String, ByVal Item() As Byte, ByVal OtherParentPKFieldValues() As String) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.AddItemBatch
            Return MyBase.Channel.AddItemBatch(EntityID, Item, OtherParentPKFieldValues)
        End Function
        
        Public Function AddItemBatchAsync(ByVal EntityID As String, ByVal Item() As Byte, ByVal OtherParentPKFieldValues() As String) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.AddItemBatchAsync
            Return MyBase.Channel.AddItemBatchAsync(EntityID, Item, OtherParentPKFieldValues)
        End Function
        
        Public Function UpdateItem(ByVal EntityID As String, ByVal Item() As Byte) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.UpdateItem
            Return MyBase.Channel.UpdateItem(EntityID, Item)
        End Function
        
        Public Function UpdateItemAsync(ByVal EntityID As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.UpdateItemAsync
            Return MyBase.Channel.UpdateItemAsync(EntityID, Item)
        End Function
        
        Public Function DeleteItem(ByVal EntityID As String, ByVal PKFieldValue As String) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.DeleteItem
            Return MyBase.Channel.DeleteItem(EntityID, PKFieldValue)
        End Function
        
        Public Function DeleteItemAsync(ByVal EntityID As String, ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.DeleteItemAsync
            Return MyBase.Channel.DeleteItemAsync(EntityID, PKFieldValue)
        End Function
        
        Public Function GetItemInfo(ByVal PKFieldValue As String) As Byte() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetItemInfo
            Return MyBase.Channel.GetItemInfo(PKFieldValue)
        End Function
        
        Public Function GetItemInfoAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetItemInfoAsync
            Return MyBase.Channel.GetItemInfoAsync(PKFieldValue)
        End Function
        
        Public Function GetSubEntityID(ByVal PKFieldValue As String) As String Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetSubEntityID
            Return MyBase.Channel.GetSubEntityID(PKFieldValue)
        End Function
        
        Public Function GetSubEntityIDAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of String) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetSubEntityIDAsync
            Return MyBase.Channel.GetSubEntityIDAsync(PKFieldValue)
        End Function
        
        Public Function SnoozeCalendarItems(ByVal PKFieldValues() As String, ByVal RemDateTime As Date) As String() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.SnoozeCalendarItems
            Return MyBase.Channel.SnoozeCalendarItems(PKFieldValues, RemDateTime)
        End Function
        
        Public Function SnoozeCalendarItemsAsync(ByVal PKFieldValues() As String, ByVal RemDateTime As Date) As System.Threading.Tasks.Task(Of String()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.SnoozeCalendarItemsAsync
            Return MyBase.Channel.SnoozeCalendarItemsAsync(PKFieldValues, RemDateTime)
        End Function
        
        Public Function CompleteCalendarItems(ByVal PKFieldValues() As String) As String() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.CompleteCalendarItems
            Return MyBase.Channel.CompleteCalendarItems(PKFieldValues)
        End Function
        
        Public Function CompleteCalendarItemsAsync(ByVal PKFieldValues() As String) As System.Threading.Tasks.Task(Of String()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.CompleteCalendarItemsAsync
            Return MyBase.Channel.CompleteCalendarItemsAsync(PKFieldValues)
        End Function
        
        Public Function GetCalendarItemsLinkInfo(ByVal PKFieldValues() As String) As Byte() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetCalendarItemsLinkInfo
            Return MyBase.Channel.GetCalendarItemsLinkInfo(PKFieldValues)
        End Function
        
        Public Function GetCalendarItemsLinkInfoAsync(ByVal PKFieldValues() As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetCalendarItemsLinkInfoAsync
            Return MyBase.Channel.GetCalendarItemsLinkInfoAsync(PKFieldValues)
        End Function
        
        Public Function GetItemDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcLinkedItemsMgr.dcFile Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetItemDoc
            Return MyBase.Channel.GetItemDoc(EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function GetItemDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcFile) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetItemDocAsync
            Return MyBase.Channel.GetItemDocAsync(EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function GetItemDocUsingOTP(ByVal OTP As String, ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As svcLinkedItemsMgr.dcFile Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetItemDocUsingOTP
            Return MyBase.Channel.GetItemDocUsingOTP(OTP, EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function GetItemDocUsingOTPAsync(ByVal OTP As String, ByVal EntityID As String, ByVal PKFieldValue As String, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcFile) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetItemDocUsingOTPAsync
            Return MyBase.Channel.GetItemDocUsingOTPAsync(OTP, EntityID, PKFieldValue, Zipped)
        End Function
        
        Public Function SetItemDoc(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcLinkedItemsMgr.dcFile, ByVal Zipped As Boolean) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.SetItemDoc
            Return MyBase.Channel.SetItemDoc(EntityID, PKFieldValue, objDCFile, Zipped)
        End Function
        
        Public Function SetItemDocAsync(ByVal EntityID As String, ByVal PKFieldValue As String, ByVal objDCFile As svcLinkedItemsMgr.dcFile, ByVal Zipped As Boolean) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.SetItemDocAsync
            Return MyBase.Channel.SetItemDocAsync(EntityID, PKFieldValue, objDCFile, Zipped)
        End Function
        
        Public Function AddMailItem(ByVal EntityID As String, ByVal ParentPKFieldValues() As String, ByVal objMailItem As svcLinkedItemsMgr.dcMailItem) As String() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.AddMailItem
            Return MyBase.Channel.AddMailItem(EntityID, ParentPKFieldValues, objMailItem)
        End Function
        
        Public Function AddMailItemAsync(ByVal EntityID As String, ByVal ParentPKFieldValues() As String, ByVal objMailItem As svcLinkedItemsMgr.dcMailItem) As System.Threading.Tasks.Task(Of String()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.AddMailItemAsync
            Return MyBase.Channel.AddMailItemAsync(EntityID, ParentPKFieldValues, objMailItem)
        End Function
        
        Public Function GetMailItem(ByVal PKFieldValue As String, ByVal NeedAttachmentsFileContent As Boolean, ByVal NeedMessageFileContent As Boolean) As svcLinkedItemsMgr.dcMailItem Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetMailItem
            Return MyBase.Channel.GetMailItem(PKFieldValue, NeedAttachmentsFileContent, NeedMessageFileContent)
        End Function
        
        Public Function GetMailItemAsync(ByVal PKFieldValue As String, ByVal NeedAttachmentsFileContent As Boolean, ByVal NeedMessageFileContent As Boolean) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcMailItem) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetMailItemAsync
            Return MyBase.Channel.GetMailItemAsync(PKFieldValue, NeedAttachmentsFileContent, NeedMessageFileContent)
        End Function
        
        Public Function SubmittedConsultantsByEMail(ByVal ConsPKValues() As String, ByVal EMailPKValues() As String) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.SubmittedConsultantsByEMail
            Return MyBase.Channel.SubmittedConsultantsByEMail(ConsPKValues, EMailPKValues)
        End Function
        
        Public Function SubmittedConsultantsByEMailAsync(ByVal ConsPKValues() As String, ByVal EMailPKValues() As String) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.SubmittedConsultantsByEMailAsync
            Return MyBase.Channel.SubmittedConsultantsByEMailAsync(ConsPKValues, EMailPKValues)
        End Function
        
        Public Function SendEMail(ByVal objMailServer As svcLinkedItemsMgr.dcSMTPServer, ByVal ParentPKValues() As String, ByVal objMailItem As svcLinkedItemsMgr.dcMailItem, ByVal ConsPKValues() As String) As svcLinkedItemsMgr.dcOBResp Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.SendEMail
            Return MyBase.Channel.SendEMail(objMailServer, ParentPKValues, objMailItem, ConsPKValues)
        End Function
        
        Public Function SendEMailAsync(ByVal objMailServer As svcLinkedItemsMgr.dcSMTPServer, ByVal ParentPKValues() As String, ByVal objMailItem As svcLinkedItemsMgr.dcMailItem, ByVal ConsPKValues() As String) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcOBResp) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.SendEMailAsync
            Return MyBase.Channel.SendEMailAsync(objMailServer, ParentPKValues, objMailItem, ConsPKValues)
        End Function
        
        Public Function ReSendEMail(ByVal objSMTPServer As svcLinkedItemsMgr.dcSMTPServer, ByVal PKFieldValue As String) As svcLinkedItemsMgr.dcOBResp Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.ReSendEMail
            Return MyBase.Channel.ReSendEMail(objSMTPServer, PKFieldValue)
        End Function
        
        Public Function ReSendEMailAsync(ByVal objSMTPServer As svcLinkedItemsMgr.dcSMTPServer, ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of svcLinkedItemsMgr.dcOBResp) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.ReSendEMailAsync
            Return MyBase.Channel.ReSendEMailAsync(objSMTPServer, PKFieldValue)
        End Function
        
        Public Function GetOutboxItems() As Byte() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetOutboxItems
            Return MyBase.Channel.GetOutboxItems
        End Function
        
        Public Function GetOutboxItemsAsync() As System.Threading.Tasks.Task(Of Byte()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetOutboxItemsAsync
            Return MyBase.Channel.GetOutboxItemsAsync
        End Function
        
        Public Sub EMailError(ByVal Subject As String, ByVal MsgBody As String, ByVal Attachments() As svcLinkedItemsMgr.dcFile) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.EMailError
            MyBase.Channel.EMailError(Subject, MsgBody, Attachments)
        End Sub
        
        Public Function EMailErrorAsync(ByVal Subject As String, ByVal MsgBody As String, ByVal Attachments() As svcLinkedItemsMgr.dcFile) As System.Threading.Tasks.Task Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.EMailErrorAsync
            Return MyBase.Channel.EMailErrorAsync(Subject, MsgBody, Attachments)
        End Function
        
        Public Function NewMLinkItem() As Byte() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.NewMLinkItem
            Return MyBase.Channel.NewMLinkItem
        End Function
        
        Public Function NewMLinkItemAsync() As System.Threading.Tasks.Task(Of Byte()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.NewMLinkItemAsync
            Return MyBase.Channel.NewMLinkItemAsync
        End Function
        
        Public Function GetMLinkItem(ByVal PKFieldValue As String) As Byte() Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetMLinkItem
            Return MyBase.Channel.GetMLinkItem(PKFieldValue)
        End Function
        
        Public Function GetMLinkItemAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.GetMLinkItemAsync
            Return MyBase.Channel.GetMLinkItemAsync(PKFieldValue)
        End Function
        
        Public Function UpdateMLinkItem(ByVal Item() As Byte) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.UpdateMLinkItem
            Return MyBase.Channel.UpdateMLinkItem(Item)
        End Function
        
        Public Function UpdateMLinkItemAsync(ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.UpdateMLinkItemAsync
            Return MyBase.Channel.UpdateMLinkItemAsync(Item)
        End Function
        
        Public Function DeleteMLinkItem(ByVal PKFieldValue As String) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.DeleteMLinkItem
            Return MyBase.Channel.DeleteMLinkItem(PKFieldValue)
        End Function
        
        Public Function DeleteMLinkItemAsync(ByVal PKFieldValue As String) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.DeleteMLinkItemAsync
            Return MyBase.Channel.DeleteMLinkItemAsync(PKFieldValue)
        End Function
        
        Public Function AddMLinkItems(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Item() As Byte) As Boolean Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.AddMLinkItems
            Return MyBase.Channel.AddMLinkItems(FromPKValues, ToPKValues, Item)
        End Function
        
        Public Function AddMLinkItemsAsync(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.AddMLinkItemsAsync
            Return MyBase.Channel.AddMLinkItemsAsync(FromPKValues, ToPKValues, Item)
        End Function
        
        Public Sub LinkSubmitted(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.LinkSubmitted
            MyBase.Channel.LinkSubmitted(FromPKValues, ToPKValues, Subject)
        End Sub
        
        Public Function LinkSubmittedAsync(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) As System.Threading.Tasks.Task Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.LinkSubmittedAsync
            Return MyBase.Channel.LinkSubmittedAsync(FromPKValues, ToPKValues, Subject)
        End Function
        
        Public Sub LinkPotential(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.LinkPotential
            MyBase.Channel.LinkPotential(FromPKValues, ToPKValues, Subject)
        End Sub
        
        Public Function LinkPotentialAsync(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) As System.Threading.Tasks.Task Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.LinkPotentialAsync
            Return MyBase.Channel.LinkPotentialAsync(FromPKValues, ToPKValues, Subject)
        End Function
        
        Public Sub LinkReceived(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.LinkReceived
            MyBase.Channel.LinkReceived(FromPKValues, ToPKValues, Subject)
        End Sub
        
        Public Function LinkReceivedAsync(ByVal FromPKValues() As String, ByVal ToPKValues() As String, ByVal Subject As String) As System.Threading.Tasks.Task Implements svcLinkedItemsMgr.ISvcLinkedItemsMgr.LinkReceivedAsync
            Return MyBase.Channel.LinkReceivedAsync(FromPKValues, ToPKValues, Subject)
        End Function
    End Class
End Namespace
