'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace svcDataMgr
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcReportReq", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcReportReq
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CategoryIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EntityIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FilterByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NeedDataField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NeedRecordCountField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NeedSchemaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageSizeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReportIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubReportIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CategoryID() As String
            Get
                Return Me.CategoryIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CategoryIDField, value) <> true) Then
                    Me.CategoryIDField = value
                    Me.RaisePropertyChanged("CategoryID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EntityID() As String
            Get
                Return Me.EntityIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntityIDField, value) <> true) Then
                    Me.EntityIDField = value
                    Me.RaisePropertyChanged("EntityID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FilterBy() As String
            Get
                Return Me.FilterByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FilterByField, value) <> true) Then
                    Me.FilterByField = value
                    Me.RaisePropertyChanged("FilterBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NeedData() As Boolean
            Get
                Return Me.NeedDataField
            End Get
            Set
                If (Me.NeedDataField.Equals(value) <> true) Then
                    Me.NeedDataField = value
                    Me.RaisePropertyChanged("NeedData")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NeedRecordCount() As Boolean
            Get
                Return Me.NeedRecordCountField
            End Get
            Set
                If (Me.NeedRecordCountField.Equals(value) <> true) Then
                    Me.NeedRecordCountField = value
                    Me.RaisePropertyChanged("NeedRecordCount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NeedSchema() As Boolean
            Get
                Return Me.NeedSchemaField
            End Get
            Set
                If (Me.NeedSchemaField.Equals(value) <> true) Then
                    Me.NeedSchemaField = value
                    Me.RaisePropertyChanged("NeedSchema")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderBy() As String
            Get
                Return Me.OrderByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderByField, value) <> true) Then
                    Me.OrderByField = value
                    Me.RaisePropertyChanged("OrderBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageNumber() As Integer
            Get
                Return Me.PageNumberField
            End Get
            Set
                If (Me.PageNumberField.Equals(value) <> true) Then
                    Me.PageNumberField = value
                    Me.RaisePropertyChanged("PageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageSize() As Integer
            Get
                Return Me.PageSizeField
            End Get
            Set
                If (Me.PageSizeField.Equals(value) <> true) Then
                    Me.PageSizeField = value
                    Me.RaisePropertyChanged("PageSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReportID() As String
            Get
                Return Me.ReportIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReportIDField, value) <> true) Then
                    Me.ReportIDField = value
                    Me.RaisePropertyChanged("ReportID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubReportID() As String
            Get
                Return Me.SubReportIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubReportIDField, value) <> true) Then
                    Me.SubReportIDField = value
                    Me.RaisePropertyChanged("SubReportID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcReportResp", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcReportResp
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DebugInfoField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HasMorePagesField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecordCountField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecordSetField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SchemaField() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DebugInfo() As Byte()
            Get
                Return Me.DebugInfoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DebugInfoField, value) <> true) Then
                    Me.DebugInfoField = value
                    Me.RaisePropertyChanged("DebugInfo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HasMorePages() As Boolean
            Get
                Return Me.HasMorePagesField
            End Get
            Set
                If (Me.HasMorePagesField.Equals(value) <> true) Then
                    Me.HasMorePagesField = value
                    Me.RaisePropertyChanged("HasMorePages")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageNumber() As Integer
            Get
                Return Me.PageNumberField
            End Get
            Set
                If (Me.PageNumberField.Equals(value) <> true) Then
                    Me.PageNumberField = value
                    Me.RaisePropertyChanged("PageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RecordCount() As Integer
            Get
                Return Me.RecordCountField
            End Get
            Set
                If (Me.RecordCountField.Equals(value) <> true) Then
                    Me.RecordCountField = value
                    Me.RaisePropertyChanged("RecordCount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RecordSet() As Byte()
            Get
                Return Me.RecordSetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RecordSetField, value) <> true) Then
                    Me.RecordSetField = value
                    Me.RaisePropertyChanged("RecordSet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Schema() As Byte()
            Get
                Return Me.SchemaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SchemaField, value) <> true) Then
                    Me.SchemaField = value
                    Me.RaisePropertyChanged("Schema")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDescField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorNumField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorDesc() As String
            Get
                Return Me.ErrorDescField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDescField, value) <> true) Then
                    Me.ErrorDescField = value
                    Me.RaisePropertyChanged("ErrorDesc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorNum() As Integer
            Get
                Return Me.ErrorNumField
            End Get
            Set
                If (Me.ErrorNumField.Equals(value) <> true) Then
                    Me.ErrorNumField = value
                    Me.RaisePropertyChanged("ErrorNum")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcDataReq", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcDataReq
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EntityIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FSMaxSearchCountField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FilterByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsFacetedSearchField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NeedDataField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NeedRecordCountField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NeedSchemaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NeedStyleMapField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PKColumnOnlyField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageSizeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SelectFieldsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SelectedIntIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WhichField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WhichIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EntityID() As String
            Get
                Return Me.EntityIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntityIDField, value) <> true) Then
                    Me.EntityIDField = value
                    Me.RaisePropertyChanged("EntityID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FSMaxSearchCount() As Integer
            Get
                Return Me.FSMaxSearchCountField
            End Get
            Set
                If (Me.FSMaxSearchCountField.Equals(value) <> true) Then
                    Me.FSMaxSearchCountField = value
                    Me.RaisePropertyChanged("FSMaxSearchCount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FilterBy() As String
            Get
                Return Me.FilterByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FilterByField, value) <> true) Then
                    Me.FilterByField = value
                    Me.RaisePropertyChanged("FilterBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsFacetedSearch() As Boolean
            Get
                Return Me.IsFacetedSearchField
            End Get
            Set
                If (Me.IsFacetedSearchField.Equals(value) <> true) Then
                    Me.IsFacetedSearchField = value
                    Me.RaisePropertyChanged("IsFacetedSearch")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NeedData() As Boolean
            Get
                Return Me.NeedDataField
            End Get
            Set
                If (Me.NeedDataField.Equals(value) <> true) Then
                    Me.NeedDataField = value
                    Me.RaisePropertyChanged("NeedData")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NeedRecordCount() As Boolean
            Get
                Return Me.NeedRecordCountField
            End Get
            Set
                If (Me.NeedRecordCountField.Equals(value) <> true) Then
                    Me.NeedRecordCountField = value
                    Me.RaisePropertyChanged("NeedRecordCount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NeedSchema() As Boolean
            Get
                Return Me.NeedSchemaField
            End Get
            Set
                If (Me.NeedSchemaField.Equals(value) <> true) Then
                    Me.NeedSchemaField = value
                    Me.RaisePropertyChanged("NeedSchema")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NeedStyleMap() As Boolean
            Get
                Return Me.NeedStyleMapField
            End Get
            Set
                If (Me.NeedStyleMapField.Equals(value) <> true) Then
                    Me.NeedStyleMapField = value
                    Me.RaisePropertyChanged("NeedStyleMap")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderBy() As String
            Get
                Return Me.OrderByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderByField, value) <> true) Then
                    Me.OrderByField = value
                    Me.RaisePropertyChanged("OrderBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PKColumnOnly() As Boolean
            Get
                Return Me.PKColumnOnlyField
            End Get
            Set
                If (Me.PKColumnOnlyField.Equals(value) <> true) Then
                    Me.PKColumnOnlyField = value
                    Me.RaisePropertyChanged("PKColumnOnly")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageNumber() As Integer
            Get
                Return Me.PageNumberField
            End Get
            Set
                If (Me.PageNumberField.Equals(value) <> true) Then
                    Me.PageNumberField = value
                    Me.RaisePropertyChanged("PageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageSize() As Integer
            Get
                Return Me.PageSizeField
            End Get
            Set
                If (Me.PageSizeField.Equals(value) <> true) Then
                    Me.PageSizeField = value
                    Me.RaisePropertyChanged("PageSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SelectFields() As String
            Get
                Return Me.SelectFieldsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SelectFieldsField, value) <> true) Then
                    Me.SelectFieldsField = value
                    Me.RaisePropertyChanged("SelectFields")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SelectedIntID() As String
            Get
                Return Me.SelectedIntIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SelectedIntIDField, value) <> true) Then
                    Me.SelectedIntIDField = value
                    Me.RaisePropertyChanged("SelectedIntID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Which() As String
            Get
                Return Me.WhichField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WhichField, value) <> true) Then
                    Me.WhichField = value
                    Me.RaisePropertyChanged("Which")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WhichID() As String
            Get
                Return Me.WhichIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WhichIDField, value) <> true) Then
                    Me.WhichIDField = value
                    Me.RaisePropertyChanged("WhichID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcDataResp", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcDataResp
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DebugInfoField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FacetResultsField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HasMorePagesField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecordCountField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecordSetField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SchemaField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StyleMapField() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DebugInfo() As Byte()
            Get
                Return Me.DebugInfoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DebugInfoField, value) <> true) Then
                    Me.DebugInfoField = value
                    Me.RaisePropertyChanged("DebugInfo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FacetResults() As Byte()
            Get
                Return Me.FacetResultsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FacetResultsField, value) <> true) Then
                    Me.FacetResultsField = value
                    Me.RaisePropertyChanged("FacetResults")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HasMorePages() As Boolean
            Get
                Return Me.HasMorePagesField
            End Get
            Set
                If (Me.HasMorePagesField.Equals(value) <> true) Then
                    Me.HasMorePagesField = value
                    Me.RaisePropertyChanged("HasMorePages")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageNumber() As Integer
            Get
                Return Me.PageNumberField
            End Get
            Set
                If (Me.PageNumberField.Equals(value) <> true) Then
                    Me.PageNumberField = value
                    Me.RaisePropertyChanged("PageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RecordCount() As Integer
            Get
                Return Me.RecordCountField
            End Get
            Set
                If (Me.RecordCountField.Equals(value) <> true) Then
                    Me.RecordCountField = value
                    Me.RaisePropertyChanged("RecordCount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RecordSet() As Byte()
            Get
                Return Me.RecordSetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RecordSetField, value) <> true) Then
                    Me.RecordSetField = value
                    Me.RaisePropertyChanged("RecordSet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Schema() As Byte()
            Get
                Return Me.SchemaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SchemaField, value) <> true) Then
                    Me.SchemaField = value
                    Me.RaisePropertyChanged("Schema")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StyleMap() As Byte()
            Get
                Return Me.StyleMapField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StyleMapField, value) <> true) Then
                    Me.StyleMapField = value
                    Me.RaisePropertyChanged("StyleMap")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="svcDataMgr.ISvcDataMgr")>  _
    Public Interface ISvcDataMgr
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetReport", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetReportResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcDataMgr.dcException), Action:="http://tempuri.org/ISvcDataMgr/GetReportdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetReport(ByVal objDCReportReq() As svcDataMgr.dcReportReq) As svcDataMgr.dcReportResp()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetReport", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetReportResponse")>  _
        Function GetReportAsync(ByVal objDCReportReq() As svcDataMgr.dcReportReq) As System.Threading.Tasks.Task(Of svcDataMgr.dcReportResp())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetSubReport", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetSubReportResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcDataMgr.dcException), Action:="http://tempuri.org/ISvcDataMgr/GetSubReportdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetSubReport(ByVal objDCReportReq As svcDataMgr.dcReportReq) As svcDataMgr.dcReportResp
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetSubReport", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetSubReportResponse")>  _
        Function GetSubReportAsync(ByVal objDCReportReq As svcDataMgr.dcReportReq) As System.Threading.Tasks.Task(Of svcDataMgr.dcReportResp)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetSubReportAsCSV", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetSubReportAsCSVResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcDataMgr.dcException), Action:="http://tempuri.org/ISvcDataMgr/GetSubReportAsCSVdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetSubReportAsCSV(ByVal objDCReportReq As svcDataMgr.dcReportReq) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetSubReportAsCSV", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetSubReportAsCSVResponse")>  _
        Function GetSubReportAsCSVAsync(ByVal objDCReportReq As svcDataMgr.dcReportReq) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetPageAsCSV", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetPageAsCSVResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcDataMgr.dcException), Action:="http://tempuri.org/ISvcDataMgr/GetPageAsCSVdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetPageAsCSV(ByVal objDCDataReq As svcDataMgr.dcDataReq) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetPageAsCSV", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetPageAsCSVResponse")>  _
        Function GetPageAsCSVAsync(ByVal objDCDataReq As svcDataMgr.dcDataReq) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetPage", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetPageResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcDataMgr.dcException), Action:="http://tempuri.org/ISvcDataMgr/GetPagedcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetPage(ByVal objDCDataReq As svcDataMgr.dcDataReq) As svcDataMgr.dcDataResp
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcDataMgr/GetPage", ReplyAction:="http://tempuri.org/ISvcDataMgr/GetPageResponse")>  _
        Function GetPageAsync(ByVal objDCDataReq As svcDataMgr.dcDataReq) As System.Threading.Tasks.Task(Of svcDataMgr.dcDataResp)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISvcDataMgrChannel
        Inherits svcDataMgr.ISvcDataMgr, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SvcDataMgrClient
        Inherits System.ServiceModel.ClientBase(Of svcDataMgr.ISvcDataMgr)
        Implements svcDataMgr.ISvcDataMgr
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetReport(ByVal objDCReportReq() As svcDataMgr.dcReportReq) As svcDataMgr.dcReportResp() Implements svcDataMgr.ISvcDataMgr.GetReport
            Return MyBase.Channel.GetReport(objDCReportReq)
        End Function
        
        Public Function GetReportAsync(ByVal objDCReportReq() As svcDataMgr.dcReportReq) As System.Threading.Tasks.Task(Of svcDataMgr.dcReportResp()) Implements svcDataMgr.ISvcDataMgr.GetReportAsync
            Return MyBase.Channel.GetReportAsync(objDCReportReq)
        End Function
        
        Public Function GetSubReport(ByVal objDCReportReq As svcDataMgr.dcReportReq) As svcDataMgr.dcReportResp Implements svcDataMgr.ISvcDataMgr.GetSubReport
            Return MyBase.Channel.GetSubReport(objDCReportReq)
        End Function
        
        Public Function GetSubReportAsync(ByVal objDCReportReq As svcDataMgr.dcReportReq) As System.Threading.Tasks.Task(Of svcDataMgr.dcReportResp) Implements svcDataMgr.ISvcDataMgr.GetSubReportAsync
            Return MyBase.Channel.GetSubReportAsync(objDCReportReq)
        End Function
        
        Public Function GetSubReportAsCSV(ByVal objDCReportReq As svcDataMgr.dcReportReq) As Byte() Implements svcDataMgr.ISvcDataMgr.GetSubReportAsCSV
            Return MyBase.Channel.GetSubReportAsCSV(objDCReportReq)
        End Function
        
        Public Function GetSubReportAsCSVAsync(ByVal objDCReportReq As svcDataMgr.dcReportReq) As System.Threading.Tasks.Task(Of Byte()) Implements svcDataMgr.ISvcDataMgr.GetSubReportAsCSVAsync
            Return MyBase.Channel.GetSubReportAsCSVAsync(objDCReportReq)
        End Function
        
        Public Function GetPageAsCSV(ByVal objDCDataReq As svcDataMgr.dcDataReq) As Byte() Implements svcDataMgr.ISvcDataMgr.GetPageAsCSV
            Return MyBase.Channel.GetPageAsCSV(objDCDataReq)
        End Function
        
        Public Function GetPageAsCSVAsync(ByVal objDCDataReq As svcDataMgr.dcDataReq) As System.Threading.Tasks.Task(Of Byte()) Implements svcDataMgr.ISvcDataMgr.GetPageAsCSVAsync
            Return MyBase.Channel.GetPageAsCSVAsync(objDCDataReq)
        End Function
        
        Public Function GetPage(ByVal objDCDataReq As svcDataMgr.dcDataReq) As svcDataMgr.dcDataResp Implements svcDataMgr.ISvcDataMgr.GetPage
            Return MyBase.Channel.GetPage(objDCDataReq)
        End Function
        
        Public Function GetPageAsync(ByVal objDCDataReq As svcDataMgr.dcDataReq) As System.Threading.Tasks.Task(Of svcDataMgr.dcDataResp) Implements svcDataMgr.ISvcDataMgr.GetPageAsync
            Return MyBase.Channel.GetPageAsync(objDCDataReq)
        End Function
    End Class
End Namespace
