'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace svcUserMgr
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcUserReq", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcUserReq
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApplyDaylightSavingsTimeField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChannelIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimeZoneIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimeZoneStandardNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ApplyDaylightSavingsTime() As Boolean
            Get
                Return Me.ApplyDaylightSavingsTimeField
            End Get
            Set
                If (Me.ApplyDaylightSavingsTimeField.Equals(value) <> true) Then
                    Me.ApplyDaylightSavingsTimeField = value
                    Me.RaisePropertyChanged("ApplyDaylightSavingsTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ChannelID() As String
            Get
                Return Me.ChannelIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChannelIDField, value) <> true) Then
                    Me.ChannelIDField = value
                    Me.RaisePropertyChanged("ChannelID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CompanyID() As String
            Get
                Return Me.CompanyIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyIDField, value) <> true) Then
                    Me.CompanyIDField = value
                    Me.RaisePropertyChanged("CompanyID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TimeZoneID() As String
            Get
                Return Me.TimeZoneIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimeZoneIDField, value) <> true) Then
                    Me.TimeZoneIDField = value
                    Me.RaisePropertyChanged("TimeZoneID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TimeZoneStandardName() As String
            Get
                Return Me.TimeZoneStandardNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimeZoneStandardNameField, value) <> true) Then
                    Me.TimeZoneStandardNameField = value
                    Me.RaisePropertyChanged("TimeZoneStandardName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserID() As String
            Get
                Return Me.UserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIDField, value) <> true) Then
                    Me.UserIDField = value
                    Me.RaisePropertyChanged("UserID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcUserResp", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcUserResp
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AuthTokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServerTimeField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AuthToken() As String
            Get
                Return Me.AuthTokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuthTokenField, value) <> true) Then
                    Me.AuthTokenField = value
                    Me.RaisePropertyChanged("AuthToken")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ServerTime() As Date
            Get
                Return Me.ServerTimeField
            End Get
            Set
                If (Me.ServerTimeField.Equals(value) <> true) Then
                    Me.ServerTimeField = value
                    Me.RaisePropertyChanged("ServerTime")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDescField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorNumField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorDesc() As String
            Get
                Return Me.ErrorDescField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDescField, value) <> true) Then
                    Me.ErrorDescField = value
                    Me.RaisePropertyChanged("ErrorDesc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorNum() As Integer
            Get
                Return Me.ErrorNumField
            End Get
            Set
                If (Me.ErrorNumField.Equals(value) <> true) Then
                    Me.ErrorNumField = value
                    Me.RaisePropertyChanged("ErrorNum")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcFile", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcFile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileContentsField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PKFieldValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CD() As String
            Get
                Return Me.CDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CDField, value) <> true) Then
                    Me.CDField = value
                    Me.RaisePropertyChanged("CD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ED() As String
            Get
                Return Me.EDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EDField, value) <> true) Then
                    Me.EDField = value
                    Me.RaisePropertyChanged("ED")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileContents() As Byte()
            Get
                Return Me.FileContentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileContentsField, value) <> true) Then
                    Me.FileContentsField = value
                    Me.RaisePropertyChanged("FileContents")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameField, value) <> true) Then
                    Me.FileNameField = value
                    Me.RaisePropertyChanged("FileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PKFieldValue() As String
            Get
                Return Me.PKFieldValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PKFieldValueField, value) <> true) Then
                    Me.PKFieldValueField = value
                    Me.RaisePropertyChanged("PKFieldValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcUser", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcUser
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppXMLVersionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApplyDaylightSavingsTimeField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DebugKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DeviceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReloginField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServerTimeField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimeZoneIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimeZoneStandardNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UTCOffsetHoursField As Single
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XBarVersionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rAppXMLField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rAuthTokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rLicenseMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rNewDBField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rNewMetaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rSessionTimeoutMinsField As Long
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AppXMLVersion() As String
            Get
                Return Me.AppXMLVersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppXMLVersionField, value) <> true) Then
                    Me.AppXMLVersionField = value
                    Me.RaisePropertyChanged("AppXMLVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ApplyDaylightSavingsTime() As Boolean
            Get
                Return Me.ApplyDaylightSavingsTimeField
            End Get
            Set
                If (Me.ApplyDaylightSavingsTimeField.Equals(value) <> true) Then
                    Me.ApplyDaylightSavingsTimeField = value
                    Me.RaisePropertyChanged("ApplyDaylightSavingsTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CompanyID() As String
            Get
                Return Me.CompanyIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyIDField, value) <> true) Then
                    Me.CompanyIDField = value
                    Me.RaisePropertyChanged("CompanyID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DebugKey() As String
            Get
                Return Me.DebugKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DebugKeyField, value) <> true) Then
                    Me.DebugKeyField = value
                    Me.RaisePropertyChanged("DebugKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Device() As String
            Get
                Return Me.DeviceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DeviceField, value) <> true) Then
                    Me.DeviceField = value
                    Me.RaisePropertyChanged("Device")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Relogin() As Boolean
            Get
                Return Me.ReloginField
            End Get
            Set
                If (Me.ReloginField.Equals(value) <> true) Then
                    Me.ReloginField = value
                    Me.RaisePropertyChanged("Relogin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ServerTime() As Date
            Get
                Return Me.ServerTimeField
            End Get
            Set
                If (Me.ServerTimeField.Equals(value) <> true) Then
                    Me.ServerTimeField = value
                    Me.RaisePropertyChanged("ServerTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TimeZoneID() As String
            Get
                Return Me.TimeZoneIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimeZoneIDField, value) <> true) Then
                    Me.TimeZoneIDField = value
                    Me.RaisePropertyChanged("TimeZoneID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TimeZoneStandardName() As String
            Get
                Return Me.TimeZoneStandardNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimeZoneStandardNameField, value) <> true) Then
                    Me.TimeZoneStandardNameField = value
                    Me.RaisePropertyChanged("TimeZoneStandardName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UTCOffsetHours() As Single
            Get
                Return Me.UTCOffsetHoursField
            End Get
            Set
                If (Me.UTCOffsetHoursField.Equals(value) <> true) Then
                    Me.UTCOffsetHoursField = value
                    Me.RaisePropertyChanged("UTCOffsetHours")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserID() As String
            Get
                Return Me.UserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIDField, value) <> true) Then
                    Me.UserIDField = value
                    Me.RaisePropertyChanged("UserID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XBarVersion() As String
            Get
                Return Me.XBarVersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XBarVersionField, value) <> true) Then
                    Me.XBarVersionField = value
                    Me.RaisePropertyChanged("XBarVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rAppXML() As Byte()
            Get
                Return Me.rAppXMLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.rAppXMLField, value) <> true) Then
                    Me.rAppXMLField = value
                    Me.RaisePropertyChanged("rAppXML")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rAuthToken() As String
            Get
                Return Me.rAuthTokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.rAuthTokenField, value) <> true) Then
                    Me.rAuthTokenField = value
                    Me.RaisePropertyChanged("rAuthToken")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rLicenseMessage() As String
            Get
                Return Me.rLicenseMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.rLicenseMessageField, value) <> true) Then
                    Me.rLicenseMessageField = value
                    Me.RaisePropertyChanged("rLicenseMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rNewDB() As Boolean
            Get
                Return Me.rNewDBField
            End Get
            Set
                If (Me.rNewDBField.Equals(value) <> true) Then
                    Me.rNewDBField = value
                    Me.RaisePropertyChanged("rNewDB")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rNewMeta() As Boolean
            Get
                Return Me.rNewMetaField
            End Get
            Set
                If (Me.rNewMetaField.Equals(value) <> true) Then
                    Me.rNewMetaField = value
                    Me.RaisePropertyChanged("rNewMeta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rSessionTimeoutMins() As Long
            Get
                Return Me.rSessionTimeoutMinsField
            End Get
            Set
                If (Me.rSessionTimeoutMinsField.Equals(value) <> true) Then
                    Me.rSessionTimeoutMinsField = value
                    Me.RaisePropertyChanged("rSessionTimeoutMins")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="svcUserMgr.ISvcUserMgr")>  _
    Public Interface ISvcUserMgr
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/Login", ReplyAction:="http://tempuri.org/ISvcUserMgr/LoginResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/LogindcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function Login(ByVal objDCUserReq As svcUserMgr.dcUserReq) As svcUserMgr.dcUserResp
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/Login", ReplyAction:="http://tempuri.org/ISvcUserMgr/LoginResponse")>  _
        Function LoginAsync(ByVal objDCUserReq As svcUserMgr.dcUserReq) As System.Threading.Tasks.Task(Of svcUserMgr.dcUserResp)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/ReplaceAppXML", ReplyAction:="http://tempuri.org/ISvcUserMgr/ReplaceAppXMLResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/ReplaceAppXMLdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function ReplaceAppXML(ByVal objDCFiles() As svcUserMgr.dcFile) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/ReplaceAppXML", ReplyAction:="http://tempuri.org/ISvcUserMgr/ReplaceAppXMLResponse")>  _
        Function ReplaceAppXMLAsync(ByVal objDCFiles() As svcUserMgr.dcFile) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/AuthUserPlus", ReplyAction:="http://tempuri.org/ISvcUserMgr/AuthUserPlusResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/AuthUserPlusdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AuthUserPlus(ByVal objDCUser As svcUserMgr.dcUser) As svcUserMgr.dcUser
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/AuthUserPlus", ReplyAction:="http://tempuri.org/ISvcUserMgr/AuthUserPlusResponse")>  _
        Function AuthUserPlusAsync(ByVal objDCUser As svcUserMgr.dcUser) As System.Threading.Tasks.Task(Of svcUserMgr.dcUser)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/CheckLicense", ReplyAction:="http://tempuri.org/ISvcUserMgr/CheckLicenseResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/CheckLicensedcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function CheckLicense(ByVal CompanyID As String, ByVal UserID As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/CheckLicense", ReplyAction:="http://tempuri.org/ISvcUserMgr/CheckLicenseResponse")>  _
        Function CheckLicenseAsync(ByVal CompanyID As String, ByVal UserID As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/GetOptions", ReplyAction:="http://tempuri.org/ISvcUserMgr/GetOptionsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/GetOptionsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetOptions(ByVal UserID As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/GetOptions", ReplyAction:="http://tempuri.org/ISvcUserMgr/GetOptionsResponse")>  _
        Function GetOptionsAsync(ByVal UserID As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/SaveOptions", ReplyAction:="http://tempuri.org/ISvcUserMgr/SaveOptionsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/SaveOptionsdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function SaveOptions(ByVal UserID As String, ByVal Options() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/SaveOptions", ReplyAction:="http://tempuri.org/ISvcUserMgr/SaveOptionsResponse")>  _
        Function SaveOptionsAsync(ByVal UserID As String, ByVal Options() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/GetOTP", ReplyAction:="http://tempuri.org/ISvcUserMgr/GetOTPResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/GetOTPdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetOTP() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/GetOTP", ReplyAction:="http://tempuri.org/ISvcUserMgr/GetOTPResponse")>  _
        Function GetOTPAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/Logout", ReplyAction:="http://tempuri.org/ISvcUserMgr/LogoutResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/LogoutdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function Logout() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/Logout", ReplyAction:="http://tempuri.org/ISvcUserMgr/LogoutResponse")>  _
        Function LogoutAsync() As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/GetUsers", ReplyAction:="http://tempuri.org/ISvcUserMgr/GetUsersResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/GetUsersdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetUsers() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/GetUsers", ReplyAction:="http://tempuri.org/ISvcUserMgr/GetUsersResponse")>  _
        Function GetUsersAsync() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/NewUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/NewUserResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/NewUserdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function NewUser() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/NewUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/NewUserResponse")>  _
        Function NewUserAsync() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/GetUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/GetUserResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/GetUserdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function GetUser(ByVal UserID As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/GetUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/GetUserResponse")>  _
        Function GetUserAsync(ByVal UserID As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/AddUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/AddUserResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/AddUserdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function AddUser(ByVal Item() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/AddUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/AddUserResponse")>  _
        Function AddUserAsync(ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/UpdateUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/UpdateUserResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/UpdateUserdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function UpdateUser(ByVal Item() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/UpdateUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/UpdateUserResponse")>  _
        Function UpdateUserAsync(ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/DeleteUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/DeleteUserResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(svcUserMgr.dcException), Action:="http://tempuri.org/ISvcUserMgr/DeleteUserdcExceptionFault", Name:="dcException", [Namespace]:="http://schemas.datacontract.org/2004/07/CBS.ClassLib")>  _
        Function DeleteUser(ByVal UserID As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISvcUserMgr/DeleteUser", ReplyAction:="http://tempuri.org/ISvcUserMgr/DeleteUserResponse")>  _
        Function DeleteUserAsync(ByVal UserID As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISvcUserMgrChannel
        Inherits svcUserMgr.ISvcUserMgr, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SvcUserMgrClient
        Inherits System.ServiceModel.ClientBase(Of svcUserMgr.ISvcUserMgr)
        Implements svcUserMgr.ISvcUserMgr
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Login(ByVal objDCUserReq As svcUserMgr.dcUserReq) As svcUserMgr.dcUserResp Implements svcUserMgr.ISvcUserMgr.Login
            Return MyBase.Channel.Login(objDCUserReq)
        End Function
        
        Public Function LoginAsync(ByVal objDCUserReq As svcUserMgr.dcUserReq) As System.Threading.Tasks.Task(Of svcUserMgr.dcUserResp) Implements svcUserMgr.ISvcUserMgr.LoginAsync
            Return MyBase.Channel.LoginAsync(objDCUserReq)
        End Function
        
        Public Function ReplaceAppXML(ByVal objDCFiles() As svcUserMgr.dcFile) As Byte() Implements svcUserMgr.ISvcUserMgr.ReplaceAppXML
            Return MyBase.Channel.ReplaceAppXML(objDCFiles)
        End Function
        
        Public Function ReplaceAppXMLAsync(ByVal objDCFiles() As svcUserMgr.dcFile) As System.Threading.Tasks.Task(Of Byte()) Implements svcUserMgr.ISvcUserMgr.ReplaceAppXMLAsync
            Return MyBase.Channel.ReplaceAppXMLAsync(objDCFiles)
        End Function
        
        Public Function AuthUserPlus(ByVal objDCUser As svcUserMgr.dcUser) As svcUserMgr.dcUser Implements svcUserMgr.ISvcUserMgr.AuthUserPlus
            Return MyBase.Channel.AuthUserPlus(objDCUser)
        End Function
        
        Public Function AuthUserPlusAsync(ByVal objDCUser As svcUserMgr.dcUser) As System.Threading.Tasks.Task(Of svcUserMgr.dcUser) Implements svcUserMgr.ISvcUserMgr.AuthUserPlusAsync
            Return MyBase.Channel.AuthUserPlusAsync(objDCUser)
        End Function
        
        Public Function CheckLicense(ByVal CompanyID As String, ByVal UserID As String) As String() Implements svcUserMgr.ISvcUserMgr.CheckLicense
            Return MyBase.Channel.CheckLicense(CompanyID, UserID)
        End Function
        
        Public Function CheckLicenseAsync(ByVal CompanyID As String, ByVal UserID As String) As System.Threading.Tasks.Task(Of String()) Implements svcUserMgr.ISvcUserMgr.CheckLicenseAsync
            Return MyBase.Channel.CheckLicenseAsync(CompanyID, UserID)
        End Function
        
        Public Function GetOptions(ByVal UserID As String) As Byte() Implements svcUserMgr.ISvcUserMgr.GetOptions
            Return MyBase.Channel.GetOptions(UserID)
        End Function
        
        Public Function GetOptionsAsync(ByVal UserID As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcUserMgr.ISvcUserMgr.GetOptionsAsync
            Return MyBase.Channel.GetOptionsAsync(UserID)
        End Function
        
        Public Function SaveOptions(ByVal UserID As String, ByVal Options() As Byte) As Boolean Implements svcUserMgr.ISvcUserMgr.SaveOptions
            Return MyBase.Channel.SaveOptions(UserID, Options)
        End Function
        
        Public Function SaveOptionsAsync(ByVal UserID As String, ByVal Options() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcUserMgr.ISvcUserMgr.SaveOptionsAsync
            Return MyBase.Channel.SaveOptionsAsync(UserID, Options)
        End Function
        
        Public Function GetOTP() As String Implements svcUserMgr.ISvcUserMgr.GetOTP
            Return MyBase.Channel.GetOTP
        End Function
        
        Public Function GetOTPAsync() As System.Threading.Tasks.Task(Of String) Implements svcUserMgr.ISvcUserMgr.GetOTPAsync
            Return MyBase.Channel.GetOTPAsync
        End Function
        
        Public Function Logout() As Boolean Implements svcUserMgr.ISvcUserMgr.Logout
            Return MyBase.Channel.Logout
        End Function
        
        Public Function LogoutAsync() As System.Threading.Tasks.Task(Of Boolean) Implements svcUserMgr.ISvcUserMgr.LogoutAsync
            Return MyBase.Channel.LogoutAsync
        End Function
        
        Public Function GetUsers() As Byte() Implements svcUserMgr.ISvcUserMgr.GetUsers
            Return MyBase.Channel.GetUsers
        End Function
        
        Public Function GetUsersAsync() As System.Threading.Tasks.Task(Of Byte()) Implements svcUserMgr.ISvcUserMgr.GetUsersAsync
            Return MyBase.Channel.GetUsersAsync
        End Function
        
        Public Function NewUser() As Byte() Implements svcUserMgr.ISvcUserMgr.NewUser
            Return MyBase.Channel.NewUser
        End Function
        
        Public Function NewUserAsync() As System.Threading.Tasks.Task(Of Byte()) Implements svcUserMgr.ISvcUserMgr.NewUserAsync
            Return MyBase.Channel.NewUserAsync
        End Function
        
        Public Function GetUser(ByVal UserID As String) As Byte() Implements svcUserMgr.ISvcUserMgr.GetUser
            Return MyBase.Channel.GetUser(UserID)
        End Function
        
        Public Function GetUserAsync(ByVal UserID As String) As System.Threading.Tasks.Task(Of Byte()) Implements svcUserMgr.ISvcUserMgr.GetUserAsync
            Return MyBase.Channel.GetUserAsync(UserID)
        End Function
        
        Public Function AddUser(ByVal Item() As Byte) As Boolean Implements svcUserMgr.ISvcUserMgr.AddUser
            Return MyBase.Channel.AddUser(Item)
        End Function
        
        Public Function AddUserAsync(ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcUserMgr.ISvcUserMgr.AddUserAsync
            Return MyBase.Channel.AddUserAsync(Item)
        End Function
        
        Public Function UpdateUser(ByVal Item() As Byte) As Boolean Implements svcUserMgr.ISvcUserMgr.UpdateUser
            Return MyBase.Channel.UpdateUser(Item)
        End Function
        
        Public Function UpdateUserAsync(ByVal Item() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements svcUserMgr.ISvcUserMgr.UpdateUserAsync
            Return MyBase.Channel.UpdateUserAsync(Item)
        End Function
        
        Public Function DeleteUser(ByVal UserID As String) As Boolean Implements svcUserMgr.ISvcUserMgr.DeleteUser
            Return MyBase.Channel.DeleteUser(UserID)
        End Function
        
        Public Function DeleteUserAsync(ByVal UserID As String) As System.Threading.Tasks.Task(Of Boolean) Implements svcUserMgr.ISvcUserMgr.DeleteUserAsync
            Return MyBase.Channel.DeleteUserAsync(UserID)
        End Function
    End Class
End Namespace
